filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/www/html/storage/logs/laravel*.log

# Comment out the Logstash output section
# output.logstash:
#   hosts: ["logstash:5044"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "elastic_password"
