version: "3.8"

services:
    app:
        build:
            context: .
        container_name: laravel-app
        volumes:
            - .:/var/www/html # Mount the Laravel project
            - ./storage/logs:/var/log/laravel # Mount Laravel's logs for Logstash
        depends_on:
            - mysql
            - elasticsearch
            - kibana
            - logstash
        networks:
            - app-network

    webserver:
        image: nginx:stable-alpine # Use Nginx as the web server
        container_name: laravel-web
        ports:
            - "8000:80" # Map host port 8000 to container's port 80
        volumes:
            - .:/var/www/html # Mount the Laravel project
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nginx configuration
        depends_on:
            - app
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - app-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
        container_name: elasticsearch
        environment:
            discovery.type: single-node
        ports:
            - "9200:9200"
        networks:
            - app-network

    kibana:
        image: docker.elastic.co/kibana/kibana:8.10.2
        container_name: kibana
        ports:
            - "5601:5601"
        networks:
            - app-network

    logstash:
        image: docker.elastic.co/logstash/logstash:8.10.2
        container_name: logstash
        volumes:
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
            - ./storage/logs:/var/log/laravel
        depends_on:
            - elasticsearch
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
