services:
    laravel-app:
        image: php:8.2-fpm
        container_name: laravel-app
        volumes:
            - ./src:/var/www/html
        networks:
            - app-network
        # No need to expose port 80, since it's not directly handling HTTP traffic

    nginx:
        image: nginx:latest
        container_name: nginx-container
        depends_on:
            - laravel-app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./src:/var/www/html
        ports:
            - "80:80" # Exposing port 80 for HTTP traffic
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
