services:
    # Laravel app service (PHP-FPM)
    app:
        build:
            context: .
        container_name: laravel-app
        volumes:
            - .:/var/www/html # Mount the Laravel project directory
            - ./storage/logs:/var/log/laravel # Mount Laravel logs for Logstash
        environment:
            - APP_URL=http://localhost
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=mysql # MySQL service name
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=user
            - DB_PASSWORD=password
        expose:
            - "9000" # Expose port internally (no need for external port mapping)
        depends_on:
            - mysql
        networks:
            - app-network

    # Nginx Web server
    webserver:
        image: nginx:stable-alpine
        container_name: laravel-web
        ports:
            - "80:80" # Map host port 80 to container's port 80
        volumes:
            - .:/var/www/html # Mount Laravel project directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nginx configuration
        depends_on:
            - app
        networks:
            - app-network

    # MySQL database service
    mysql:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        expose:
            - "3306" # Expose MySQL port internally (no external port mapping)
        networks:
            - app-network

    # phpMyAdmin service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            - PMA_HOST=mysql # MySQL service name (phpMyAdmin connects to MySQL)
            - PMA_USER=user
            - PMA_PASSWORD=password
        ports:
            - "8080:80" # Map host port 8080 to phpMyAdmin container port 80
        networks:
            - app-network
        depends_on:
            - mysql
        restart: unless-stopped

networks:
    app-network:
        driver: bridge
