services:
    laravel-app:
        image: php:8.2-fpm
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx-container
        depends_on:
            - laravel-app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        ports:
            - "80:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
