version: "3.8"

services:
    app:
        build:
            context: .
        container_name: laravel-app
        volumes:
            - .:/var/www/html # Mount the entire Laravel project
            - ./storage/logs:/var/log/laravel # Mount Laravel's storage/logs directory for Logstash
        ports:
            - "8000:9000" # Expose the app on port 8000 for Laravel
        depends_on:
            - mysql
            - elasticsearch
            - kibana
            - logstash # App depends on Logstash for logging
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - app-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3 # Use a compatible version (adjusted)
        container_name: elasticsearch
        environment:
            discovery.type: single-node
        ports:
            - "9200:9200"
        networks:
            - app-network

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.3 # Use a compatible version (adjusted)
        container_name: kibana
        ports:
            - "5601:5601"
        networks:
            - app-network

    logstash:
        image: docker.elastic.co/logstash/logstash:7.9.3 # Updated to a compatible version
        container_name: logstash
        volumes:
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf # Mount the Logstash config file
            - ./storage/logs:/var/log/laravel # Mount Laravel's storage/logs directory for Logstash to read logs
        depends_on:
            - elasticsearch
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
