version: "3.8"

services:
    app:
        build:
            context: .
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        ports:
            - "8000:9000"
        depends_on:
            - mysql
            - elasticsearch
            - kibana
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - app-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: elasticsearch
        environment:
            discovery.type: single-node
        ports:
            - "9200:9200"
        networks:
            - app-network

    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.0
        container_name: kibana
        ports:
            - "5601:5601"
        networks:
            - app-network

    logstash:
        image: docker.elastic.co/logstash/logstash:7.10.0
        container_name: logstash
        volumes:
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        depends_on:
            - elasticsearch
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
