services:
    # Laravel app service
    app:
        build:
            context: .
        container_name: laravel-app
        volumes:
            - .:/var/www/html # Mount the Laravel project directory
            - ./storage/logs:/var/log/laravel # Mount Laravel logs for Logstash
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:d3G8x1u68ubU7h0pZH4WLbgZdW+lzp1wGXApGK+oj+s= # Use your actual APP_KEY here
            - DB_CONNECTION=mysql
            - DB_HOST=mysql # MySQL service name
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=user
            - DB_PASSWORD=password
        depends_on:
            - mysql
            - elasticsearch
            - kibana
            - logstash
        networks:
            - app-network

    # Web server (Nginx)
    webserver:
        image: nginx:stable-alpine
        container_name: laravel-web
        ports:
            - "8000:80" # Map host port 8000 to container's port 80
        volumes:
            - .:/var/www/html # Mount Laravel project directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nginx configuration
        depends_on:
            - app
        networks:
            - app-network

    # MySQL database service
    mysql:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - app-network

    # Elasticsearch service
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
        container_name: elasticsearch
        environment:
            discovery.type: single-node
        ports:
            - "9200:9200"
        networks:
            - app-network

    # Kibana service (for Elasticsearch visualization)
    kibana:
        image: docker.elastic.co/kibana/kibana:8.10.2
        container_name: kibana
        ports:
            - "5601:5601"
        networks:
            - app-network

    # Logstash service
    logstash:
        image: docker.elastic.co/logstash/logstash:8.10.2
        container_name: logstash
        volumes:
            - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
            - ./storage/logs:/var/log/laravel # Mount Laravel logs for Logstash to read
        depends_on:
            - elasticsearch
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
