#api.http.host: "0.0.0.0"
#xpack.monitoring.enabled: true
#pipeline.buffer.type: heap
#xpack.management.elasticsearch.hosts: ["http://elasticsearch:9200"]

http.host: 0.0.0.0
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
